group:
  - files:
      - quartz/
      - package.json
      - package-lock.json
      - source: .github/workflows/
        dest: .github/workflows/
        exclude: |
          sync_file.yml
          ci.yaml
    repos: |
      ObsidianPublisher/Publisher-Quartz
      ObsidianPublisher/docs
